// Digit shapes, ingredient art, and the recipe book.
//
// Recipes are DATA. A stage names a primitive from js/stages.js plus the art it
// uses; it never names a number. The number comes from js/range.js at runtime, so
// any recipe can run at any difficulty. See docs/BRIEF.md.

// ---------- digits ----------
// Each digit as chunky SVG strokes in a 100x100 box, the same convention ABC Town
// uses for letters: cap top y=12, baseline y=90, so a digit is 78 tall on a 100 box.
// Build-a-Numeral scatters these strokes as draggable pieces, so splitting a stroke
// in two makes a digit harder and merging two makes it easier.
const DIGIT_STROKES = {
  0: ['M50 12 A26 39 0 0 0 50 90', 'M50 12 A26 39 0 0 1 50 90'],
  1: ['M30 30 L52 12', 'M52 12 V90', 'M30 90 H74'],
  2: ['M24 32 A24 24 0 0 1 70 44', 'M70 44 L24 90', 'M24 90 H78'],
  3: ['M24 28 A24 20 0 0 1 62 40 A18 14 0 0 1 42 51', 'M42 51 A20 16 0 0 1 64 66 A26 22 0 0 1 24 82'],
  4: ['M62 12 L20 64', 'M20 64 H78', 'M62 40 V90'],
  5: ['M72 12 H32', 'M32 12 V44', 'M32 44 H50 A23 23 0 0 1 50 90 H26'],
  6: ['M64 16 A34 40 0 0 0 23 68', 'M23 68 A25 21 0 0 1 73 68 A25 21 0 0 1 23 68'],
  7: ['M22 12 H78', 'M78 12 L40 90'],
  8: ['M50 12 A20 19 0 0 0 50 50 A20 19 0 0 0 50 12', 'M50 50 A24 20 0 0 0 50 90 A24 20 0 0 0 50 50'],
  9: ['M36 84 A34 40 0 0 0 77 34', 'M77 34 A25 21 0 0 1 27 34 A25 21 0 0 1 77 34'],
};

// A two-digit number's strokes, laid out side by side in a 200x100 box.
function numeralStrokes(n) {
  const s = String(n);
  if (s.length === 1) return DIGIT_STROKES[s].map(d => ({ d, dx: 50 }));
  return s.split('').flatMap((ch, i) => DIGIT_STROKES[ch].map(d => ({ d, dx: i * 100 })));
}

// ---------- art ----------
// Ingredients, portions, utensils and recipe icons are SVG files in assets/art/,
// generated by tools/build_art.py and used as <img> so Safari rasterises each once
// however many copies a stage holds. Vessels are inlined in js/vessels.js because
// their insides animate. Nothing here is an emoji.
const artUrl = id => `assets/art/${id}.svg`;

// ---------- the recipe book ----------
// `scene` dresses the kitchen behind each recipe: a patterned wall, a worktop, and a
// few props scattered on it. Objects floating on flat cream was the single biggest
// thing making the game look unfinished next to the reference. Pattern is one of
// gingham | stripe | tile | dot (see .p-* in css/style.css); props are art ids.
// Stages name a primitive and its art. `n` is injected at runtime by the range model.
// `say` lines use {n} for the chosen number; the voice key is built from the stage id.
const RECIPES = [
  {
    id: 'pizza', name: 'Pizza', icon: 'icon-pizza', color: '#e8542f',
    scene: { wall: '#ffc9a8', pattern: 'tile',    counter: '#c58a52', props: ['tomato', 'basil', 'cheese'] },
    blurb: 'Roll it, top it, bake it.',
    stages: [
      { id: 'flour',  primitive: 'scoop-bag',     item: 'scoop',  vessel: 'bowl', say: 'Scoop {n} cups of flour into the bowl.' },
      { id: 'eggs',   primitive: 'crack-eggs',                    vessel: 'bowl', say: 'Crack {n} eggs into the bowl.' },
      { id: 'stir',   primitive: 'stir-bowl',     tool: 'whisk',  vessel: 'bowl', say: 'Stir the bowl {n} times!' },
      { id: 'roll',   primitive: 'count-gesture', gesture: 'roll', tool: 'rollingpin',   vessel: 'dough', say: 'Roll the dough {n} times!' },
      { id: 'bake',   primitive: 'set-dial',      device: 'oven',                     say: 'Set the oven to {n}.' },
      { id: 'top',    primitive: 'count-place',   item: 'pepperoni', vessel: 'pizza', say: 'Put {n} pepperoni on the pizza.' },
      { id: 'slice',  primitive: 'cut-into',      vessel: 'pizza', shape: 'wedge',     say: 'Cut the pizza into {n} slices.' },
      { id: 'serve',  primitive: 'match-1to1',    item: 'slice',                      say: 'Give everyone a slice!' },
    ],
  },
  {
    id: 'cupcakes', name: 'Cupcakes', icon: 'icon-cupcakes', color: '#e85fa2',
    scene: { wall: '#ffcfe2', pattern: 'stripe',  counter: '#e6dfd2', props: ['cherry', 'sprinkle', 'egg'] },
    blurb: 'A tray of ten, then some more.',
    stages: [
      { id: 'flour',  primitive: 'count-place',   item: 'scoop',    vessel: 'bowl', say: 'Put {n} scoops of flour in the bowl.' },
      { id: 'eggs',   primitive: 'count-place',   item: 'egg',      vessel: 'bowl', say: 'Crack {n} eggs into the bowl.' },
      { id: 'fill',   primitive: 'count-place',   item: 'case',     vessel: 'tray', say: 'Fill {n} cupcake cases.' },
      { id: 'stir',   primitive: 'count-gesture', gesture: 'stir', tool: 'spoon',  vessel: 'bowl', say: 'Stir the mixture {n} times!' },
      { id: 'bake',   primitive: 'set-dial',      device: 'oven',                   say: 'Set the oven to {n}.' },
      { id: 'cherry', primitive: 'count-place',   item: 'cherry',   vessel: 'tray', say: 'Put {n} cherries on top.' },
      { id: 'serve',  primitive: 'match-1to1',    item: 'cupcake',                  say: 'Give everyone a cupcake!' },
    ],
  },
  {
    id: 'sandwich', name: 'Sandwich', icon: 'icon-sandwich', color: '#d79a3c',
    scene: { wall: '#b6e3d6', pattern: 'gingham', counter: '#d9b485', props: ['lettuce', 'butter', 'tomato'] },
    blurb: 'No oven needed.',
    stages: [
      { id: 'bread',  primitive: 'count-place',   item: 'bread',   vessel: 'plate', say: 'Put {n} slices of bread on the plate.' },
      { id: 'spread', primitive: 'count-gesture', gesture: 'spread', tool: 'knife', vessel: 'plate', say: 'Spread the butter {n} times!' },
      { id: 'ham',    primitive: 'count-place',   item: 'ham',     vessel: 'plate', say: 'Add {n} pieces of ham.' },
      { id: 'cut',    primitive: 'cut-into',      vessel: 'plate', shape: 'strip',   say: 'Cut the sandwich into {n} pieces.' },
      { id: 'serve',  primitive: 'match-1to1',    item: 'sandwich',                 say: 'Give everyone a sandwich!' },
    ],
  },
  {
    id: 'smoothie', name: 'Smoothie', icon: 'icon-smoothie', color: '#8e44ff',
    scene: { wall: '#d4c7f2', pattern: 'dot',     counter: '#e9e7f0', props: ['banana', 'strawberry', 'berry'] },
    blurb: 'Whizz it up and pour.',
    stages: [
      { id: 'fruit',  primitive: 'count-place', item: 'strawberry', vessel: 'blender', say: 'Put {n} strawberries in the blender.' },
      { id: 'berry',  primitive: 'count-place', item: 'berry',      vessel: 'blender', say: 'Add {n} blueberries.' },
      { id: 'whizz',  primitive: 'set-dial',    device: 'blender',                     say: 'Turn the blender to {n}.' },
      { id: 'pour',   primitive: 'count-place', item: 'cup',        vessel: 'plate',   say: 'Pour {n} cups of smoothie.' },
      { id: 'serve',  primitive: 'match-1to1',  item: 'cup',                           say: 'Give everyone a smoothie!' },
    ],
  },
  {
    id: 'pancakes', name: 'Pancakes', icon: 'icon-pancakes', color: '#c9772f',
    scene: { wall: '#ffe2a6', pattern: 'gingham', counter: '#c58a52', props: ['butter', 'berry', 'cherry'] },
    blurb: 'Flip them and stack them high.',
    stages: [
      { id: 'flour',  primitive: 'count-place',   item: 'scoop',  vessel: 'bowl', say: 'Put {n} scoops of flour in the bowl.' },
      { id: 'whisk',  primitive: 'count-gesture', gesture: 'whisk', tool: 'whisk', vessel: 'bowl', say: 'Whisk the batter {n} times!' },
      { id: 'cook',   primitive: 'set-dial',      device: 'oven',                 say: 'Set the stove to {n}.' },
      { id: 'flip',   primitive: 'count-gesture', gesture: 'flip', tool: 'spatula', vessel: 'pan', say: 'Flip the pancake {n} times!' },
      { id: 'berries',primitive: 'count-place',   item: 'berry',  vessel: 'plate', say: 'Put {n} berries on the stack.' },
      { id: 'serve',  primitive: 'match-1to1',    item: 'pancake',                say: 'Give everyone a pancake!' },
    ],
  },
];

// The kitchen cast: who turns up to be served, and who fills the café.
// Generated by tools/build_cast.py — one shared kit (head, eyes, brows, mouth, arms,
// legs) with a different face and outfit each, so eight people cost about as much to
// draw as one. Referenced as <img> rather than inlined: Safari rasterises each file
// once and reuses it, which matters when six share a stage.
const CAST = [
  { id: 'pip',   name: 'Pip',   color: '#e8503a', job: 'the chef' },
  { id: 'bea',   name: 'Bea',   color: '#f0a6c0', job: 'the baker' },
  { id: 'ollie', name: 'Ollie', color: '#5d8c3f', job: 'the farmer' },
  { id: 'mimi',  name: 'Mimi',  color: '#ff5fa2', job: 'the little one' },
  { id: 'gus',   name: 'Gus',   color: '#ff9e2c', job: 'the builder' },
  { id: 'nell',  name: 'Nell',  color: '#c0563a', job: 'the gardener' },
  { id: 'rory',  name: 'Rory',  color: '#2f4f8f', job: 'the postie' },
  { id: 'tilly', name: 'Tilly', color: '#b89ad4', job: 'everyone\'s nan' },
];
CAST.forEach(c => { c.img = `assets/cast/${c.id}.svg`; });
