#!/usr/bin/env bash
# Assemble the static site into ./deploy — only what the game needs at runtime.
# Used by Netlify (see netlify.toml).
set -euo pipefail
cd "$(dirname "$0")"

rm -rf deploy
mkdir -p deploy/css deploy/js deploy/assets/voice deploy/assets/cast
cp index.html deploy/
cp css/* deploy/css/
cp js/* deploy/js/
cp assets/cast/*.svg deploy/assets/cast/
# The voice clips are generated by tools/generate_voice.py and may not exist yet;
# the game falls back to browser text-to-speech without them.
if compgen -G "assets/voice/*" > /dev/null; then cp assets/voice/* deploy/assets/voice/; fi

echo "Built deploy/: $(find deploy -type f | wc -l) files"
